### ISSUE TITLE
Ошибка разметки

### ISSUE THREAD

**Issue by Hell13Cat** [timas130/campfire-web#11]
Картинка залезла на другой комментарий.

[Пост с ошибкой](https://campfire.moe/post/4916389) | [PasteBin с исходным кодом](https://pastebin.com/RxnqmWzr)

Скриншоты:
![Screenshot_2](https://user-images.githubusercontent.com/46496367/215686552-5b54f32e-c263-4073-b438-1288ee792e84.png)
![Screenshot_1](https://user-images.githubusercontent.com/46496367/215686563-0e7dce0f-6a64-4ddc-879c-4c250c7938d9.png)

**Comment by timas130** [comment]
Теперь понял.
